# Generated by Django 2.2.4 on 2019-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Student Name')),
                ('rollno', models.IntegerField()),
                ('dob', models.DateTimeField(verbose_name='Birthday')),
                ('fname', models.CharField(max_length=30, verbose_name="Father's Name")),
                ('mname', models.CharField(max_length=30, verbose_name="Mother's Name")),
            ],
        ),
    ]
